spring:
  datasource:
    url: jdbc:h2:mem:testdb; MODE=MYSQL;
    driver: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MariaDBDialect
    datasource-platform: org.hibernate.dialect.H2Dialect
